### PR TITLE
feat: support custom initializationOptions

### PR DESCRIPTION
**Pull request by chrismwendt**
This lets consumers provide custom `initializationOptions` for all workspaces.

This subsumes https://github.com/sourcegraph/lsp-client/pull/11 which included workarounds for go-langserver prior to https://github.com/sourcegraph/go-langserver/pull/373

### CODE REVIEW

**Review by felixfbecker — APPROVED** [review]

**Comment by chrismwendt** [comment]
@felixfbecker Do I need to bump the `beta` branch to trigger CI to make a release?

**Comment by felixfbecker** [comment]
yep

**Comment by chrismwendt** [comment]
`1.1.0-beta.2` doesn't seem right. The latest is `2.0.0-beta.1`. Is there another branch I need to update?

**Comment by felixfbecker** [comment]
That's weird indeed. Will investigate

**Comment by felixfbecker** [comment]
Filed https://github.com/semantic-release/semantic-release/issues/1191

**Comment by felixfbecker** [comment]
I released `2.0.0-beta.2` manually

**Comment by chrismwendt** [comment]
Ok, thanks. I'm seeing a source map warning, not sure if it's related:

> [serve] ⚠️  Could not load source file "../../src/features/feature.ts" in source map of "../node_modules/@sourcegraph/lsp-client/dist/features/feature.js".

**Comment by felixfbecker** [comment]
Well sources are not published nor inlined, but that doesn't sound related to the release issue?

**Comment by chrismwendt** [comment]
Gotcha, yeah it's not related.

**Pull request merged**
